//Java program to demonstrate how Arithmetic Exception is thrown.

public class TryCatchEx1ArithmeticException {

    public static void main(String[] args) {

        int data = 50 / 0; //may throw exception

        System.out.println("rest of the code");

    }

}
